
server:
  port: 8080

spring:
  jpa:
    hibernate:
      dll-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none


  datasource:
    url: jdbc:postgresql://localhost:5435/statement_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  cloud:
    loadbalancer:
       ribbon:
        enable: false

jwt:
  header:
    Authorization
  secret:
    light
  time:
   #min
    access-expired:
      100
    refresh-expired:
      30000
    accept:
      300
  issuer:
    app

  